### ISSUE TITLE
Failed installation with MPI support

### ISSUE THREAD

**Issue by cerd9235** [Yandell-Lab/maker#10]
Hello,

I have been trying to install Maker with MPI support for a while. I have not been successful to install it from source and have been using conda for most of the dependencies following this instructions:

http://felixgrewe.github.io/linux_cookbook/install_maker.html

Everything is fine until I get to the ./Build install where I get the following error:

Configuring MAKER with MPI support
Running Mkbootstrap for MPI ()
chmod 644 "MPI.bs"
"/data/users/juan/miniconda2/envs/maker/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- MPI.bs blib/arch/auto/Parallel/Application/MPI/MPI.bs 644
"/data/users/juan/miniconda2/envs/maker/bin/perl" "/data/users/juan/miniconda2/envs/maker/lib/5.26.2/ExtUtils/xsubpp"  -typemap "/data/users/juan/miniconda2/envs/maker/lib/5.26.2/ExtUtils/typemap"   MPI.xs > MPI.xsc
mv MPI.xsc MPI.c
/scratch/users/juan/biotools/openmpi/bin/mpicc -c  -I"/data/users/juan/biotools/maker/src" -I/scratch/users/juan/biotools/openmpi/include -D_REENTRANT -D_GNU_SOURCE --sysroot=/tmp/build/80754af9/perl_1527832170752/_build_env/x86_64-conda_cos6-linux-gnu/sysroot -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2  -O2   -DVERSION=\"0.00\" -DXS_VERSION=\"0.00\" -fPIC --sysroot=/tmp/build/80754af9/perl_1527832170752/_build_env/x86_64-conda_cos6-linux-gnu/sysroot "-I/data/users/juan/miniconda2/envs/maker/lib/5.26.2/x86_64-linux-thread-multi/CORE"   MPI.c
In file included from MPI.xs:2:0:
/data/users/juan/miniconda2/envs/maker/lib/5.26.2/x86_64-linux-thread-multi/CORE/perl.h:694:10: fatal error: sys/types.h: No such file or directory
 #include <sys/types.h>
          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:333: MPI.o] Error 1

A problem was encountered while attempting to compile and install your Inline
C code. The command that failed was:
  "make > out.make 2>&1" with error code 2

The build directory was:
/data/users/juan/biotools/maker/src/blib/build/Parallel/Application/MPI

To debug the problem, cd to the build directory, and inspect the output files.

Environment PATH = '/scratch/users/juan/biotools/snap/Zoe:/scratch/users/juan/biotools/openmpi/bin:/scratch/users/juan/miniconda2/envs/maker/bin:/scratch/users/juan/miniconda2/condabin:/scratch/users/juan/biotools/RepeatMasker:/scratch/users/juan/biotools/go/bin:/usr/local/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/afs/bx.psu.edu/user/j/jdc81/bin:/afs/bx.psu.edu/user/j/jdc81/bin/x86_64:/afs/bx.psu.edu/software/bin:/afs/bx.psu.edu/misc/apps/bin:/afs/bx.psu.edu/misc/apps/x86_64/bin:/afs/bx.psu.edu/user/j/jdc81/go/bin:/scratch/users/juan/biotools/go/bin:/afs/bx.psu.edu/user/j/jdc81/bin:/scratch/users/juan/biotools/snap/Zoe:/scratch/users/juan/biotools/openmpi/bin:/scratch/users/juan/miniconda2/envs/maker/bin:/scratch/users/juan/miniconda2/condabin:/scratch/users/juan/biotools/RepeatMasker:/scratch/users/juan/biotools/go/bin:/usr/local/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/afs/bx.psu.edu/user/j/jdc81/bin:/afs/bx.psu.edu/user/j/jdc81/bin/x86_64:/afs/bx.psu.edu/software/bin:/afs/bx.psu.edu/misc/apps/bin:/afs/bx.psu.edu/misc/apps/x86_64/bin:/afs/bx.psu.edu/user/j/jdc81/go/bin:/scratch/users/juan/biotools/go/bin:/afs/bx.psu.edu/user/j/jdc81/bin:/home/cholt/Developer/circos/bin:/home/cholt/Developer/maker/trunk/exe/augustus/bin:/home/cholt/Developer/maker/trunk/exe/snap:/home/cholt/Developer/maker/trunk/exe/RepeatMasker:/home/cholt/Developer/maker/trunk/exe/exonerate/bin:/home/cholt/Developer/maker/trunk/MWAS/bin:/home/cholt/Developer/maker/trunk/bin:/home/cholt/Developer/maker/trunk/exe/wublast:/home/cholt/Developer/maker/trunk/exe/mpich2/bin:/home/cholt/Developer/Seq_Analysis/bin:/usr/local/gmod/schema/bin:/usr/local/gmod/apollo/bin:/usr/local/circos/bin:/usr/local/eval:/usr/local/tophat/bin:/usr/local/bowtie:/usr/local/arbol/bin:/usr/local/phylobayes/data:/usr/local/Gblocks:/usr/local/clustalw:/usr/local/phylip/exe:/usr/local/iprscan/bin:/usr/local/cegma/bin:/usr/local/gmps:/usr/local/gmes:/usr/local/fgenesh/bin:/usr/local/maker/bin:/usr/local/Seq_Analysis/bin:/usr/local/my_apps:/usr/local/libtool/bin:/usr/local/automake/bin:/usr/local/autoconf/bin:/home/cholt/.gvm/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/cholt/.composer/vendor/bin:/usr/local/grails-2.5.5/bin:/usr/local/gradle-3.5/bin:/var/lib/snapd/snap/bin:/usr/pgsql-9.6/bin:/bin:/usr/local/samtools:/usr/local/tabix:/usr/local/vcftools/bin:/home/cholt/Developer/samtools:/home/cholt/Developer/tabix:/home/cholt/Developer/vcftools/bin:/usr/local/bin'
 at /data/users/juan/biotools/maker/src/lib/Parallel/Application/MPI.pm line 236.
	...propagated at /data/users/juan/miniconda2/envs/maker/lib/site_perl/5.26.2/Inline/C.pm line 869.
 at /data/users/juan/biotools/maker/src/lib/Parallel/Application/MPI.pm line 256.
	Parallel::Application::MPI::_bind("/scratch/users/juan/biotools/openmpi/bin/mpicc", "/scratch/users/juan/biotools/openmpi/include", "blib", "") called at /data/users/juan/biotools/maker/src/inc/lib/MAKER/Build.pm line 279
	MAKER::Build::ACTION_build(MAKER::Build=HASH(0x55e48d63b380)) called at /data/users/juan/biotools/maker/src/inc/bundle/Module/Build/Base.pm line 1877
	Module::Build::Base::_call_action(MAKER::Build=HASH(0x55e48d63b380), "build") called at /data/users/juan/biotools/maker/src/inc/bundle/Module/Build/Base.pm line 1860
	Module::Build::Base::dispatch(MAKER::Build=HASH(0x55e48d63b380), "build") called at /data/users/juan/biotools/maker/src/inc/lib/MAKER/Build.pm line 482
	MAKER::Build::ACTION_install(MAKER::Build=HASH(0x55e48d63b380)) called at /data/users/juan/biotools/maker/src/inc/bundle/Module/Build/Base.pm line 1877
	Module::Build::Base::_call_action(MAKER::Build=HASH(0x55e48d63b380), "install") called at /data/users/juan/biotools/maker/src/inc/bundle/Module/Build/Base.pm line 1865
	Module::Build::Base::dispatch(MAKER::Build=HASH(0x55e48d63b380)) called at ./Build line 62

I have searched for way to fix it, including installing some libraries or setting C_INCLUDE_PATH or CPLUS_INCLUDE_PATH paths. This temporally solves the issue, but a new error appears stating crti.o not found found. I have also tried installing it without conda and receive similar issues (in fact a little more difficult because of our system's configuration).  

I do not have this issue when configuring without MPI support, but since the genome I am trying to annotate is quite big, I would like to be able to parallelize the process. 

Any suggestions of what could be causing the issue and how to fix it?

Thanks in advance

**Comment by isnmn** [comment]
Hey, I have the same problem. Did you solve this?

**Comment by carsonhh** [comment]
Please install MAKER using the download at github or here (https://www.yandell-lab.org/software/maker.html) and not by using miniconda.

Thanks,
Carson

**Comment by carsonhh** [comment]
You may also have to disable miniconda before installing/using maker as it can sometimes break perl and MPI, and I can't debug miniconda related conflicts

**Comment by isnmn** [comment]
I installed it via yandell website, not conda. But I still have this error. Which version of MPI does MAKER support? I am using HPC so I have no "memory" issues going on. The only thing that comes to my mind is the OpenMPI version for MAKER. Can you clarify please? @carsonhh

**Comment by srynobio** [comment]
@isnmn I would review the following found in the INSTALL instructions for the correct version of [MPI](https://github.com/Yandell-Lab/maker/blob/master/INSTALL#L41)
