### ISSUE TITLE
maker exited on signal 11 (Segmentation fault)

### ISSUE THREAD

**Issue by Toral-Manvar** [Yandell-Lab/maker#15]
We have been trying to run maker v3.01.04 using openMPI4.1.4 on HPC.

Using following command for analysis:

``mpiexec -mca btl ^openib -np 40  -base  round1_result round1_maker_opts.ctl  maker_bopts.ctl maker_exe_test_harsh.ctl `
`
However getting error:
Caught signal 11 (Segmentation fault: address not mapped to object at address 0x5a4)

Tried number of things but nothing is working.
Please help.

**Comment by carsonhh** [comment]
See faults will be coming either from OpenMPI or Perl as opposed to MAKER itself (something they link is out of sink with the kernel).  You will likely need to install OpenMPI or Perl again then reinstall MAKER. MAKER will need to recompile bindings to OpenMPI using the new mpicc from the new OpenMPI install.  Perlbrew (https://perlbrew.pl) is the easiest way to load a second Perl installation. You can also try installing MPICH as opposed to OpenMPI.
