### ISSUE TITLE
maker is only using 1 thread during RepeatMasker stage

### ISSUE THREAD

**Issue by fanhuan** [Yandell-Lab/maker#17]
Hi,

I set `cpus=40 #max number of cpus to use in BLAST and RepeatMasker (not for MPI, leave 1 when using MPI)` in `maker_opts.ctl` and from the log I do see the `-pa 40` option was present in the RepeatMasker cmd: `cd /tmp/maker_zUd8tM; /opt/RepeatMasker/RepeatMasker /opt/work/maker.output/maker_datastore/27/AC/chr4//theVoid.chr4/86/chr4.869.consensi%2Efa%2Eclassified%2Empi%2E10%2E9.specific -dir /opt/work/maker.output/maker_datastore/27/AC/chr4//theVoid.chr4/86 -pa 40 -lib /opt/work/maker.output/mpi_blastdb/consensi%2Efa%2Eclassified.mpi.10/consensi%2Efa%2Eclassified.mpi.10.9`. 

However, from my observation via `top` or `htop`, it is always only using 1 thread. Is this because I am actually running in mpi mode? What I was running was just `maker ***` without `mpiexec`. But you do see the mpi in the paths of my RepeatMasker command. How can I use multiple cores? Do I have to use `mpiexec`? Any instruction would he high appreciated!

Best,
Huan

**Comment by carsonhh** [comment]
If running under MPI and using a scheduler like SLURM or others, they will automatically enable proccess affinity/binding.  With processor affinity, each MPI process along with its threads is “bound” to a specific subset of processing resources (cores, packages, etc.). That is, the operating system will constrain that process to run on only that subset. So if you give MPI 1 cpu, all subprocess run on that 1 CPU regardless of how many threads they try to launch.  Either don't use MPI to launch maker or alter the MPI settings through command line flags and environmental variables to disable process affinity/binding.
