### ISSUE TITLE
DBD::SQLite::db selectcol_arrayref failed: database is locked at xxx

### ISSUE THREAD

**Issue by dongzhang0725** [Yandell-Lab/maker#2]
Dear developers,

Thank you for developing MAKER, my favorate annotation tool. Recently, I encounterred a problem when I ran annotation on a 900M genome, the error message is listed below:

`DBD::SQLite::db selectcol_arrayref failed: database is locked at /apps/zhangdong/miniconda3_2/envs/maker/bin/../lib/GFFDB.pm line 525.`

I have searched on google and found a discussion regarding the same problem in http://yandell-lab.org/pipermail/maker-devel_yandell-lab.org/2012-August/000230.html. I checked my filesystem, and confirmed that it is non-NFS.

MAKER is installed using `mamba create -n maker -c bioconda -c conda-forge maker`, and the MAKER version is 3.01.03, the MPICH version is 3.4.3.

Could you help me find out what happened with my problem?

Thank you for your help!

Sincerely,

Dong

**Comment by carsonhh** [comment]
The lock should only exist when the DB is generated. You may have 2 separate maker processes with a race condition.

Test for mpi communication. Submit a job as normal  —> 'mpiexec maker -help' or 'mpiexec -n <cpu_count> maker -help'

If you get multiple help messages, then MPI communicator is the issue (connection ring is down). If you get a single message, it’s fine.

You then want to search for another active MAKER process on each machine —> ps auxww | grep maker

Finally, you can delete any '.db’ files under the output directory to force it to rebuild the DB on the next run.  The DB holds a representation of an input GFF3 file, so it regenerates quickly.

—Carson

**Comment by dongzhang0725** [comment]
Dear @carsonhh 

Thank you for your quick answer, I checked as you suggested:

1. I ran `mpiexec -n 3 maker -help`, I only get one help message.
2. I ran `ps auxww | grep maker`, and yes I get multiple maker processes, this is expexted, because I ran MAKER using MPI: `mpirun -n 80 maker -base MAKER2nd`.
3. Regarding the '.db' files, I checked, I only have one "MAKER2nd.db" file in the results folder, and importantly, before I ran MAKER using the above command, there is no '.db' file in the output directory, after `STATUS: Setting up database for any GFF3 input...`, it is generated, after this and the repeat masking, I get 'DBD::SQLite::db selectcol_arrayref failed' error .

   ![image](https://user-images.githubusercontent.com/15956921/163659917-f905584b-2238-44e3-a8f7-310cd967155b.png)

I am not sure how can I delete '.db’ files when MAKER is running.

Thanks for your time! 

Best,

Dong

**Comment by Threeman8** [comment]
@dongzhang0725 hello,
Do you get any idea to solve this problem now?
Thanks in advance

**Comment by carsonhh** [comment]
A couple of other options. You set TMP= in the control files or you sent TMPDIR in your environment to in memory virtual disk or to an NFS filesystem. Last thing to try is install maker outside of bioconda.  The bioconda recipe does modify MAKER a bit or modify perl libraries and can cause issues in certain situations.
