### ISSUE TITLE
did not finish on the last run and must be erased

### ISSUE THREAD

**Issue by okendojo** [Yandell-Lab/maker#4]
I have generated my repeat library and when I use it to analyze my data I get the above error. I have googled and I am not getting a clear answer. I am attaching the log file with the detailed error for your convenience. Could you have a look and advise me on the way forward.
[log.zip](https://github.com/Yandell-Lab/maker/files/10114822/log.zip)

**Comment by carsonhh** [comment]
The message means that the last run failed, so the output must be deleted before it retries. Look further up the error log for the cause. The zip file is empty so I cannot review the STDERR log

**Comment by okendojo** [comment]
I have deleted the output file and it is still now running. Have a look at the log. The following is the error that I keep on getting:
```bash
--Next Contig--

RepeatMasker::createLib(): Error invoking /usr/local/apps/hmmer/3.2.1/bin//hmmpress on file /tmp/maker_rz4bs8/RM_21653.TueNov291223382022/rm_lib%2Efasta.mpi.10.0.
doing repeat masking
```
[runlog.zip](https://github.com/Yandell-Lab/maker/files/10115789/runlog.zip)

**Comment by carsonhh** [comment]
Error -->

```
RepeatMasker::createLib(): Error invoking /usr/local/apps/hmmer/3.2.1/bin//hmmpress on file /tmp/maker_cjRqQm/RM_43792.TueNov291045412022/repeats-families%2Efa.mpi.10.0
```

You can run the RepetMasker command yourself outside of maker using one of the command sin the STDERR -->
```
/usr/local/apps/repeatmasker/4.1.3-p1/RepeatMasker /vf/users/okendojo/paradisfishProject/annotation/anno_round_2.maker.output/anno_round_2_datastore/13/63/ptg000007l//theVoid.ptg000007l/0/ptg000007l.0.repeats-families%2Efa%2Empi%2E10%2E0.specific -dir /vf/users/okendojo/paradisfishProject/annotation/anno_round_2.maker.output/anno_round_2_datastore/13/63/ptg000007l//theVoid.ptg000007l/0 -pa 32 -lib /vf/users/okendojo/paradisfishProject/annotation/anno_round_2.maker.output/mpi_blastdb/repeats-families%2Efa.mpi.10/repeats-families%2Efa.mpi.10.0
```

My guess is either the input fasta has a formatting issue or RepeatMasker has an install issue. Run It outside of MAKER using one of the commands MAKER shows, and see what errors occur
