### ISSUE TITLE
used custom gene model in maker

### ISSUE THREAD

**Issue by okendojo** [Yandell-Lab/maker#5]
I am doing the annotation of an organism which does not have it's gene model in augustus `species` directory. We have our custom gene model that we would like to use. How can I use this in maker?

**Comment by carsonhh** [comment]
You can put the model in the Augustus config directory then use the species name or set a new confog directory be setting AUGUSTUS_CONFIG_PATH according to augustus documentation.

—Carson

**Comment by okendojo** [comment]
I copied my gene model to the `species` folder the added `export AUGUSTUS_CONFIG_PATH:path/to/config` in my `~/.bashrc` and it worked.
